services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - jobhub-net

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "Jobhub123@"
      MYSQL_DATABASE: job_hub
      MYSQL_USER: jobhub
      MYSQL_PASSWORD: "123ABC@"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jobhub-net

  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - jobhub-net

networks:
  jobhub-net:

volumes:
  mysql_data:
